#
###################################
# Site wide configuration
####################################
#
title: xuana
email:
description: meu blog, minhas regras
url: https://joanasouza.github.io
keywords: ["blog", "jekyll", "tech", "programming"]

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
